package com.jayjaylab.androiddemo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.jayjaylab.androiddemo.Path;

import com.jayjaylab.androiddemo.PathDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pathDaoConfig;

    private final PathDao pathDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pathDaoConfig = daoConfigMap.get(PathDao.class).clone();
        pathDaoConfig.initIdentityScope(type);

        pathDao = new PathDao(pathDaoConfig, this);

        registerDao(Path.class, pathDao);
    }
    
    public void clear() {
        pathDaoConfig.getIdentityScope().clear();
    }

    public PathDao getPathDao() {
        return pathDao;
    }

}
