package com.jayjaylab.androiddemo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table path.
 */
public class Path {

    private Long id;
    /** Not-null value. */
    private String gpxPath;
    /** Not-null value. */
    private String startTime;
    /** Not-null value. */
    private String endTime;

    public Path() {
    }

    public Path(Long id) {
        this.id = id;
    }

    public Path(Long id, String gpxPath, String startTime, String endTime) {
        this.id = id;
        this.gpxPath = gpxPath;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getGpxPath() {
        return gpxPath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGpxPath(String gpxPath) {
        this.gpxPath = gpxPath;
    }

    /** Not-null value. */
    public String getStartTime() {
        return startTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /** Not-null value. */
    public String getEndTime() {
        return endTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

}
